FROM php:8.5-apache

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN install-php-extensions intl pdo_mysql mysqli fileinfo curl

RUN curl -sSk https://getcomposer.org/installer | php -- --disable-tls && \
    mv composer.phar /usr/local/bin/composer

RUN apt update && apt install -yqq nodejs npm

COPY . /var/www/

COPY ./docker/apache.conf /etc/apache2/sites-available/000-default.conf

RUN cd /var/www && \
    composer install

RUN mkdir -p /var/www/var/cache /var/www/var/log && \
    chown -R www-data:www-data /var/www/var && \
    chmod -R 775 /var/www/var

WORKDIR /var/www/

EXPOSE 80